# Generated by Django 5.1.7 on 2025-04-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneReview',
        ),
    ]
